export const environment = {
  production: true,
  apiBaseLink: 'https://api.safetouch.com.bd',
  ftpBaseLink: 'https://ftp.safetouch.com.bd',
  appBaseUrl: '/',
  userBaseUrl: '/account',
  userLoginUrl: '/login',
  adminLoginUrl: 'admin/login',
  adminBaseUrl: 'admin',
  vendorBaseUrl: 'vendor',
  vendorLoginUrl: 'vendor/login',
  // sslIpnUrl: 'https://api.safetouch.com.bd/api/payment-ssl/ipn',
  firebaseConfig: {
    apiKey: '/',
    authDomain: '/',
    projectId: '/',
    storageBucket: '/',
    messagingSenderId: '/',
    appId: '/',
    measurementId: '/',
  },
  VERSION: 2,
};
